spring:
  application:
    name: instrutor-facil

  mvc:
    problemdetails:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5433/instrutor-facil
    username: postgres
    password: 86065542
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none  # Mude para 'none' temporariamente
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: false  # Adicione esta linha

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5433/instrutor-facil  # Adicione estas linhas
    user: postgres
    password: 86065542